dictionaries = [
    "en_us",
    "ru",
]
words = [
    "egui",
    "gruvbox",
    "kum",
    "kumir",
    "swapchain",
    "vello",
    "wasi",
    "wgpu",
    "алг",
    "вещ",
    "кц",
    "нц",
]
