// Code generated by wit-bindgen-go. DO NOT EDIT.

package core

// This file contains wasmimport and wasmexport declarations for "zu:engine@0.1.0".

//go:wasmimport zu:engine/core@0.1.0 info
//go:noescape
func wasmimport_Info(text0 *uint8, text1 uint32)

//go:wasmimport zu:engine/core@0.1.0 warn
//go:noescape
func wasmimport_Warn(text0 *uint8, text1 uint32)

//go:wasmimport zu:engine/core@0.1.0 error
//go:noescape
func wasmimport_Error(text0 *uint8, text1 uint32)

//go:wasmimport zu:engine/core@0.1.0 debug
//go:noescape
func wasmimport_Debug(text0 *uint8, text1 uint32)

//go:wasmimport zu:engine/core@0.1.0 trace
//go:noescape
func wasmimport_Trace(text0 *uint8, text1 uint32)
