// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package core represents the imported interface "zu:engine/core@0.1.0".
package core

import (
	"go.bytecodealliance.org/cm"
)

// Info represents the imported function "info".
//
//	info: func(text: string)
//
//go:nosplit
func Info(text string) {
	text0, text1 := cm.LowerString(text)
	wasmimport_Info((*uint8)(text0), (uint32)(text1))
	return
}

// Warn represents the imported function "warn".
//
//	warn: func(text: string)
//
//go:nosplit
func Warn(text string) {
	text0, text1 := cm.LowerString(text)
	wasmimport_Warn((*uint8)(text0), (uint32)(text1))
	return
}

// Error represents the imported function "error".
//
//	error: func(text: string)
//
//go:nosplit
func Error(text string) {
	text0, text1 := cm.LowerString(text)
	wasmimport_Error((*uint8)(text0), (uint32)(text1))
	return
}

// Debug represents the imported function "debug".
//
//	debug: func(text: string)
//
//go:nosplit
func Debug(text string) {
	text0, text1 := cm.LowerString(text)
	wasmimport_Debug((*uint8)(text0), (uint32)(text1))
	return
}

// Trace represents the imported function "trace".
//
//	trace: func(text: string)
//
//go:nosplit
func Trace(text string) {
	text0, text1 := cm.LowerString(text)
	wasmimport_Trace((*uint8)(text0), (uint32)(text1))
	return
}
