package zu:engine@0.1.0;

interface core {
    info: func(text: string);
    warn: func(text: string);
    error: func(text: string);
    debug: func(text: string);
    trace: func(text: string);
}

world zu-mod {
    import core;

    export init: func();
    export update: func() -> result<_, string>;
}
