// Code generated by wit-bindgen-go. DO NOT EDIT.

package zumod

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "zu:engine@0.1.0".

//go:wasmexport init
//export init
func wasmexport_Init() {
	Exports.Init()
	return
}

//go:wasmexport update
//export update
func wasmexport_Update() (result *cm.Result[string, struct{}, string]) {
	result_ := Exports.Update()
	result = &result_
	return
}
